config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '' => 'default#home', as: 'home'

  get 'users/show' => 'user#show_user', as: 'show_user'

  get 'users/list' => 'user#list_user', as: 'list_user'

  get 'users/add_friend/:id' => 'user#add_friend', as: 'add_friend', :constraints => { :id => /\d+/ }

  get 'users/already_friend' => 'user#already_friend', as: 'already_friend'
  

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :target, class_name: "User"
  belongs_to :source, class_name: "User"
  validates :target_id, presence: true
  validates :source_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :active_friends, class_name: "Friend",
  foreign_key: "target_id",
  dependent: :destroy


  has_many :is_friends, through: :active_friends, source: :source

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/default_controller.rb
class DefaultController < ApplicationController

  def home
  end

  
end

app/controllers/user_controller.rb
# coding: utf-8
class UserController < ApplicationController

  def show_user
    #oblige l utilisateur a etre connecté
    @user = current_user
    if @user.blank?
      redirect_to home_path
    end

    #recupere la liste d association
    @friend_list = ::Friend.where(source_id: @user.id)
    @user_list = []
    @friend_list.each do |friend|
      # pour chaque association, on recupere avec qui elle est faite
      @user_list.push( User.find_by id: friend.target_id )
    end
    
  end


  def list_user
    @users = ::User.all
  end

  
  def add_friend
    #oblige l utilisateur a etre connecté
    @user = current_user
    if @user.blank?
      redirect_to home_path
    end

    # on essaye de recuperer avec qui on veut etre amis, sinon on est redirigé sur home
    @target_id = params[:id]
    @target_user = User.find_by id: @target_id
    if @target_user.blank?
      redirect_to home_path
    end

    # est on deja ami avec cette personne ? si oui redirection si non on créer la relation
    @friend = Friend.find_by source_id: @user.id, target_id: @target_user.id
    if @friend.blank?
      Friend.create(source_id: @user.id, target_id: @target_user.id)
      redirect_to show_user_path
    else
      redirect_to already_friend_path
    end
  end
  
  def already_friend
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/default_helper.rb
module DefaultHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/default/form_item.html.erb
<p>Création d'item</p>

<%= form_tag "/create_item", method: "post" do %>
<input type="text" name="name" />
<input type="text" name="desc" />
<input type="submit" value="Ajouterun item" />
<% end %>

app/views/default/home.html.erb
<p>Ceci est la page d'accueil !!!</p>

app/views/default/list_item.html.erb
<p>Liste des items :</p>

	<% @items.each do |current_item| %>
 <%= link_to current_item.name, controller: "default", action: "show_item", id: current_item.id %>
  <br/>
<% end %>

app/views/default/show_item.html.erb
<p>Show Item :</p>
<ul>
<li>Name : <%= @item.name %></li>
<li>Desc : <%= @item.desc %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    


   
   
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    
    
  <title>RubyUser</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head>



  
<body>
  <header>
    <div class="navbar-fixed">
      <nav>
	<div class="nav-wrapper" id ="header">

	  <div>
	    <div>
	      <ul id="main_nav" class="right hide-on-med-and-down">

		
		<li><%= link_to "Home", home_path %></li>
		<li><%= link_to "User List", list_user_path %><li>
		  <% if user_signed_in? %>

		<li><%= link_to "Profile", show_user_path %></li>
		<li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>

		
		  <% else %>

		  <li><%= link_to "Connection", new_user_session_path %></li>
		  <li><%= link_to "Subscription", new_user_registration_path %></li>

		  <% end %>
		  
	      </ul>
	    </div>
	  </div>
      </nav>
      </div>
  </header>
  

<%= yield %>



<footer class="page-footer red darken-3">
  <div class="container">
    <div class="row">

      <div class="col l4 offset-l2 s12">
	<h5 class="white-text">Liens</h5>
	<ul>
	  <li><a class="grey-text text-lighten-3" href="#"> <img height="42" width="42" class="brand-logo" src="https://www.facebook.com/images/fb_icon_325x325.png" /></a></li>
	  <li><a class="grey-text text-lighten-3" href="#"><img height="42" width="42" class="brand-logo" src="http://www.freelargeimages.com/wp-content/uploads/2015/05/Twitter_Logo_Hd_Png_03.png" alt=""></a></li>
	</ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright" id="footer_copyright">
    <div class="container">
      © 2016 Copyright RubyOnRails
    </div>
  </div>
</footer>
<!--
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="../../../front_end/static/js/materialize.min.js"></script>
{% include 'material/includes/material_css.html' %}
<script src= "material/js/jquery-2.2.0.js"></script>
{% include 'material/includes/material_js.html' %}
-->

</body>
</html>

app/views/user/already_friend.html.erb
"Utilisateur déja dans votre liste d'amis"</br>
<%= link_to "Retour à la liste utilisateurs", list_user_path %>

app/views/user/list_user.html.erb
<ul>
<h2>User List :</h2>
<% @users.each do |user| %> 
<li><%= user.email %> <%= link_to "add_friend", add_friend_path(:id => user.id) %></li>
<% end %>
</ul>

app/views/user/show_user.html.erb
<p>Show User :</p>
<ul>
<li>email : <%= current_user.email %></li>
</ul>

<ul><h2>Friend list: </h2>
  <% if @user_list  %>

  <% @user_list.each do |user| %>
  <li><%= user.email %></li>  </br>
  <% end %>
  <% end %>
  <h2>End of friend list</h2></ul>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>